### ISSUE TITLE
Copy from textarea does not work

### ISSUE THREAD

**Issue by phenomen** [nikolai-cc/svu#6]
I've tried a couple of ways but none copies the content of textarea. `copy` works fine with other elements (div, p, pre, etc).
```html
<textarea
id="copyArea"
bind:value={fixedCopy}
/>
```
```html
<textarea
id="copyArea">
{fixedCopy}
</textarea>
```

```html
<button use:copy={'#copyArea'}>	Copy </button>
```

**Comment by nikolai-cc** [comment]
Thanks for filing! I'll take a look at it asap 🙂

**Comment by nikolai-cc** [comment]
I have just pushed a fix for this! Both methods should work in `/svu` version 0.1.5 😊
